give up waiting and merge changeset 1194 from BSPsplit branch: use public GLPK api routines for reading GMPL files; add GMPL example model and unittest routine for GMPL reader

diff --git a/CoinUtils/configure b/CoinUtils/configure
--- a/CoinUtils/configure
+++ b/CoinUtils/configure
@@ -472,7 +472,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX F77 ADD_FFLAGS DBG_FFLAGS OPT_FFLAGS FFLAGS ac_ct_F77 MPIF77 FLIBS EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS COINUTILSSRCDIR COINUTILSOBJDIR COINUTILSDOCDIR COIN_HAS_COINUTILS_TRUE COIN_HAS_COINUTILS_FALSE GMPLINCDIR GMPLLIB COIN_HAS_GMPL_TRUE COIN_HAS_GMPL_FALSE GMPLOBJDIR COIN_BUILD_GLPK_TRUE COIN_BUILD_GLPK_FALSE ASLLIB ASL_CPPFLAGS COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE COIN_HAS_BLAS_TRUE COIN_HAS_BLAS_FALSE COIN_BUILD_BLAS_TRUE COIN_BUILD_BLAS_FALSE COIN_HAS_LAPACK_TRUE COIN_HAS_LAPACK_FALSE COIN_BUILD_LAPACK_TRUE COIN_BUILD_LAPACK_FALSE COINUTILS_LIBADD COIN_HAS_ZLIB_TRUE COIN_HAS_ZLIB_FALSE LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX F77 ADD_FFLAGS DBG_FFLAGS OPT_FFLAGS FFLAGS ac_ct_F77 MPIF77 FLIBS EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS COINUTILSSRCDIR COINUTILSOBJDIR COINUTILSDOCDIR COIN_HAS_COINUTILS_TRUE COIN_HAS_COINUTILS_FALSE GLPKINCDIR GLPKLIB COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE GLPKOBJDIR COIN_BUILD_GLPK_TRUE COIN_BUILD_GLPK_FALSE ASLLIB ASL_CPPFLAGS COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE COIN_HAS_BLAS_TRUE COIN_HAS_BLAS_FALSE COIN_BUILD_BLAS_TRUE COIN_BUILD_BLAS_FALSE COIN_HAS_LAPACK_TRUE COIN_HAS_LAPACK_FALSE COIN_BUILD_LAPACK_TRUE COIN_BUILD_LAPACK_FALSE COINUTILS_LIBADD COIN_HAS_ZLIB_TRUE COIN_HAS_ZLIB_FALSE LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1122,7 +1122,7 @@ Optional Features:
                           Otherwise its value can be overridden at runtime
                           using the COINUTILS_MEMPOOL_MAXPOOLED environment
                           variable.
-  --enable-gmpl-libcheck use disable-gmpl-libcheck to skip the
+  --enable-glpk-libcheck use disable-glpk-libcheck to skip the
                           link check at configuration time
   --enable-gnu-packages   compile with GNU packages (disabled by default)
 
@@ -1139,8 +1139,8 @@ Optional Packages:
                           both]
   --with-tags[=TAGS]
                           include additional configurations [automatic]
-  --with-gmpl-incdir specify the header file directory for library Gmpl
-  --with-gmpl-lib specify the flags used to link with the library Gmpl
+  --with-glpk-incdir specify the header file directory for library Glpk
+  --with-glpk-lib specify the flags used to link with the library Glpk
   --with-asldir           specify path to AMPL solver directory (or BUILD for
                           compilation, or "no" for disabling AMPL)
   --with-blas             specify BLAS library (or BUILD for compilation)
@@ -28481,69 +28481,68 @@ use_thirdpartyglpk=no
 # library don't force a ThirdParty build, let the error propagate.
 
 
-
-  echo "$as_me:$LINENO: checking if user provides library for Gmpl" >&5
-echo $ECHO_N "checking if user provides library for Gmpl... $ECHO_C" >&6
+  echo "$as_me:$LINENO: checking if user provides library for Glpk" >&5
+echo $ECHO_N "checking if user provides library for Glpk... $ECHO_C" >&6
 
 # Check for header file directory
 
 
-# Check whether --with-gmpl-incdir or --without-gmpl-incdir was given.
-if test "${with_gmpl_incdir+set}" = set; then
-  withval="$with_gmpl_incdir"
-  GMPLINCDIR=`cd $withval; pwd`
+# Check whether --with-glpk-incdir or --without-glpk-incdir was given.
+if test "${with_glpk_incdir+set}" = set; then
+  withval="$with_glpk_incdir"
+  GLPKINCDIR=`cd $withval; pwd`
 fi;
 
 # Check for library directory
 
 
-# Check whether --with-gmpl-lib or --without-gmpl-lib was given.
-if test "${with_gmpl_lib+set}" = set; then
-  withval="$with_gmpl_lib"
-  GMPLLIB=$withval
+# Check whether --with-glpk-lib or --without-glpk-lib was given.
+if test "${with_glpk_lib+set}" = set; then
+  withval="$with_glpk_lib"
+  GLPKLIB=$withval
 fi;
 
 # Switch to disable library check if requested
 
-  # Check whether --enable-gmpl-libcheck or --disable-gmpl-libcheck was given.
-if test "${enable_gmpl_libcheck+set}" = set; then
-  enableval="$enable_gmpl_libcheck"
-  gmpl_libcheck=$enableval
+  # Check whether --enable-glpk-libcheck or --disable-glpk-libcheck was given.
+if test "${enable_glpk_libcheck+set}" = set; then
+  enableval="$enable_glpk_libcheck"
+  glpk_libcheck=$enableval
 else
-  gmpl_libcheck=yes
+  glpk_libcheck=yes
 fi;
 
 # At this point, if we're going to use the library, both LBRYINCDIR and
 # LBRYLIB must be defined and not empty.
 
-  if test x"$GMPLINCDIR" != x || test x"$GMPLLIB" != x; then
-    if test x"$GMPLINCDIR" = x || test x"$GMPLLIB" = x; then
-      { { echo "$as_me:$LINENO: error: You need to specify both an include directory and link flags to use library Gmpl. Use --with-gmpl-incdir of environment variable $GMPLINCDIR to specify the include directory. Use --with-gmpl-lib or environment variable $GMPLLIB to specify link flags." >&5
-echo "$as_me: error: You need to specify both an include directory and link flags to use library Gmpl. Use --with-gmpl-incdir of environment variable $GMPLINCDIR to specify the include directory. Use --with-gmpl-lib or environment variable $GMPLLIB to specify link flags." >&2;}
+  if test x"$GLPKINCDIR" != x || test x"$GLPKLIB" != x; then
+    if test x"$GLPKINCDIR" = x || test x"$GLPKLIB" = x; then
+      { { echo "$as_me:$LINENO: error: You need to specify both an include directory and link flags to use library Glpk. Use --with-glpk-incdir of environment variable $GLPKINCDIR to specify the include directory. Use --with-glpk-lib or environment variable $GLPKLIB to specify link flags." >&5
+echo "$as_me: error: You need to specify both an include directory and link flags to use library Glpk. Use --with-glpk-incdir of environment variable $GLPKINCDIR to specify the include directory. Use --with-glpk-lib or environment variable $GLPKLIB to specify link flags." >&2;}
    { (exit 1); exit 1; }; }
     fi
-    coin_has_gmpl=true
+    coin_has_glpk=true
     echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
   else
-    coin_has_gmpl=false
+    coin_has_glpk=false
     echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
   fi
 
 # If we have instructions for use, consider header and link checks.
 
-  if test $coin_has_gmpl = true; then
+  if test $coin_has_glpk = true; then
 
 # If argument 3 (file) is given, check for the file. Typically this will be a
 # header file, but that's not assumed.
 
-    if test -r $GMPLINCDIR/glpmpl.h; then
+    if test -r $GLPKINCDIR/glpk.h; then
 
   :
 else
-  { { echo "$as_me:$LINENO: error: Cannot find file glpmpl.h in $GMPLINCDIR" >&5
-echo "$as_me: error: Cannot find file glpmpl.h in $GMPLINCDIR" >&2;}
+  { { echo "$as_me:$LINENO: error: Cannot find file glpk.h in $GLPKINCDIR" >&5
+echo "$as_me: error: Cannot find file glpk.h in $GLPKINCDIR" >&2;}
    { (exit 1); exit 1; }; }
   :
 fi
@@ -28556,19 +28555,19 @@ fi
 # Force the use of C as the best single choice amongst C++, C, and Fortran.
 # Obviously, this has limits.
 
-    if test x"$gmpl_libcheck" != xno; then
+    if test x"$glpk_libcheck" != xno; then
 	   coin_save_LIBS="$LIBS"
-	   LIBS="$GMPLLIB $ADDLIBS"
-	   coin_GMPL_link=no
+	   LIBS="$GLPKLIB $ADDLIBS"
+	   coin_GLPK_link=no
 	   ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-	   for fnm in _glp_mpl_initialize glp_mpl_initialize ; do
-	     echo "$as_me:$LINENO: checking whether symbol $fnm is available with GMPL" >&5
-echo $ECHO_N "checking whether symbol $fnm is available with GMPL... $ECHO_C" >&6
+	   for fnm in _glp_lpx_simplex glp_lpx_simplex ; do
+	     echo "$as_me:$LINENO: checking whether symbol $fnm is available with GLPK" >&5
+echo $ECHO_N "checking whether symbol $fnm is available with GLPK... $ECHO_C" >&6
 	     cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -28616,7 +28615,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (exit $ac_status); }; }; then
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-		  coin_GMPL_link=yes
+		  coin_GLPK_link=yes
 		  break
 else
   echo "$as_me: failed program was:" >&5
@@ -28634,11 +28633,11 @@ ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
-	   if test x"$coin_GMPL_link" = xyes ; then
+	   if test x"$coin_GLPK_link" = xyes ; then
 	     LIBS="$coin_save_LIBS"
 	   else
-	     { { echo "$as_me:$LINENO: error: Cannot find symbol(s) _glp_mpl_initialize glp_mpl_initialize with GMPL" >&5
-echo "$as_me: error: Cannot find symbol(s) _glp_mpl_initialize glp_mpl_initialize with GMPL" >&2;}
+	     { { echo "$as_me:$LINENO: error: Cannot find symbol(s) _glp_lpx_simplex glp_lpx_simplex with GLPK" >&5
+echo "$as_me: error: Cannot find symbol(s) _glp_lpx_simplex glp_lpx_simplex with GLPK" >&2;}
    { (exit 1); exit 1; }; }
 	   fi
 	 fi
@@ -28648,10 +28647,10 @@ echo "$as_me: error: Cannot find symbol(s) _glp_mpl_initialize glp_mpl_initializ
 # the necessary link flags to ADDLIBS and define the preprocessor symbol
 # COIN_HAS_LBRY.
 
-    ADDLIBS="$GMPLLIB $ADDLIBS"
+    ADDLIBS="$GLPKLIB $ADDLIBS"
 
 cat >>confdefs.h <<\_ACEOF
-#define COIN_HAS_GMPL 1
+#define COIN_HAS_GLPK 1
 _ACEOF
 
   fi
@@ -28663,18 +28662,19 @@ _ACEOF
 
 
 
-if test $coin_has_gmpl = true; then
-  COIN_HAS_GMPL_TRUE=
-  COIN_HAS_GMPL_FALSE='#'
+if test $coin_has_glpk = true; then
+  COIN_HAS_GLPK_TRUE=
+  COIN_HAS_GLPK_FALSE='#'
 else
-  COIN_HAS_GMPL_TRUE='#'
-  COIN_HAS_GMPL_FALSE=
+  COIN_HAS_GLPK_TRUE='#'
+  COIN_HAS_GLPK_FALSE=
 fi
 
 
- if test x"$coin_has_gmpl" = xfalse && test x"$GMPLLIB" = x ; then
+ if test x"$coin_has_glpk" = xfalse && test x"$GLPKLIB" = x ; then
    use_thirdpartyglpk=try
  fi
+
 
 # If the user has supplied an external library, use it. Otherwise, consider
 # a build in ThirdParty/Glpk. If we build, assume we get both glpk and gmpl.
@@ -28698,19 +28698,19 @@ if test x"$use_thirdpartyglpk" = xtry ; then
 # exists).
 
   if test x"$use_thirdpartyglpk" = xbuild ; then
-    GMPLINCDIR="$coin_glpksrcdir/glpk/include"
+    GLPKINCDIR="$coin_glpksrcdir/glpk/include"
 
 
 cat >>confdefs.h <<\_ACEOF
-#define COIN_HAS_GMPL 1
+#define COIN_HAS_GLPK 1
 _ACEOF
 
-    coin_has_gmpl=true
-    gmpl_libcheck=no
-    GMPLOBJDIR=`cd $coin_glpkobjdir; pwd`
+    coin_has_glpk=true
+    glpk_libcheck=no
+    GLPKOBJDIR=`cd $coin_glpkobjdir; pwd`
 
-    { echo "$as_me:$LINENO: Using Gmpl in ThirdParty/Glpk" >&5
-echo "$as_me: Using Gmpl in ThirdParty/Glpk" >&6;}
+    { echo "$as_me:$LINENO: Using Glpk in ThirdParty/Glpk" >&5
+echo "$as_me: Using Glpk in ThirdParty/Glpk" >&6;}
   fi
 fi
 
@@ -28718,12 +28718,12 @@ fi
 
 
 
-if test x"$coin_has_gmpl" = xtrue; then
-  COIN_HAS_GMPL_TRUE=
-  COIN_HAS_GMPL_FALSE='#'
+if test x"$coin_has_glpk" = xtrue; then
+  COIN_HAS_GLPK_TRUE=
+  COIN_HAS_GLPK_FALSE='#'
 else
-  COIN_HAS_GMPL_TRUE='#'
-  COIN_HAS_GMPL_FALSE=
+  COIN_HAS_GLPK_TRUE='#'
+  COIN_HAS_GLPK_FALSE=
 fi
 
 
@@ -28740,6 +28740,9 @@ fi
 
 if test x"$use_thirdpartyglpk" = xbuild; then
   COINUTILS_LIBADD="../../ThirdParty/Glpk/libcoinglpk.la $COINUTILS_LIBADD"
+  if test -e $GLPKOBJDIR/glpk_addlibs.txt ; then
+    ADDLIBS="`cat $GLPKOBJDIR/glpk_addlibs.txt` $ADDLIBS"
+  fi
 fi
 
 #############################################################################
@@ -33557,6 +33560,22 @@ _ACEOF
 fi
 
 
+echo "$as_me:$LINENO: checking whether this is a VPATH configuration" >&5
+echo $ECHO_N "checking whether this is a VPATH configuration... $ECHO_C" >&6
+if test `cd $srcdir; pwd` != `pwd`; then
+  coin_vpath_config=yes;
+else
+  coin_vpath_config=no;
+fi
+echo "$as_me:$LINENO: result: $coin_vpath_config" >&5
+echo "${ECHO_T}$coin_vpath_config" >&6
+
+
+if test $coin_vpath_config = yes; then
+  coin_vpath_link_files="$coin_vpath_link_files test/plan.mod"
+fi
+
+
 ##############################################################################
 #                   Finishing up by writing all the output                   #
 ##############################################################################
@@ -33768,17 +33787,17 @@ echo "$as_me: error: conditional \"COIN_HAS_COINUTILS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${COIN_HAS_GMPL_TRUE}" && test -z "${COIN_HAS_GMPL_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_GMPL\" was never defined.
+if test -z "${COIN_HAS_GLPK_TRUE}" && test -z "${COIN_HAS_GLPK_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_GLPK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"COIN_HAS_GMPL\" was never defined.
+echo "$as_me: error: conditional \"COIN_HAS_GLPK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${COIN_HAS_GMPL_TRUE}" && test -z "${COIN_HAS_GMPL_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_GMPL\" was never defined.
+if test -z "${COIN_HAS_GLPK_TRUE}" && test -z "${COIN_HAS_GLPK_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_GLPK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"COIN_HAS_GMPL\" was never defined.
+echo "$as_me: error: conditional \"COIN_HAS_GLPK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -34503,11 +34522,11 @@ s,@COINUTILSOBJDIR@,$COINUTILSOBJDIR,;t t
 s,@COINUTILSDOCDIR@,$COINUTILSDOCDIR,;t t
 s,@COIN_HAS_COINUTILS_TRUE@,$COIN_HAS_COINUTILS_TRUE,;t t
 s,@COIN_HAS_COINUTILS_FALSE@,$COIN_HAS_COINUTILS_FALSE,;t t
-s,@GMPLINCDIR@,$GMPLINCDIR,;t t
-s,@GMPLLIB@,$GMPLLIB,;t t
-s,@COIN_HAS_GMPL_TRUE@,$COIN_HAS_GMPL_TRUE,;t t
-s,@COIN_HAS_GMPL_FALSE@,$COIN_HAS_GMPL_FALSE,;t t
-s,@GMPLOBJDIR@,$GMPLOBJDIR,;t t
+s,@GLPKINCDIR@,$GLPKINCDIR,;t t
+s,@GLPKLIB@,$GLPKLIB,;t t
+s,@COIN_HAS_GLPK_TRUE@,$COIN_HAS_GLPK_TRUE,;t t
+s,@COIN_HAS_GLPK_FALSE@,$COIN_HAS_GLPK_FALSE,;t t
+s,@GLPKOBJDIR@,$GLPKOBJDIR,;t t
 s,@COIN_BUILD_GLPK_TRUE@,$COIN_BUILD_GLPK_TRUE,;t t
 s,@COIN_BUILD_GLPK_FALSE@,$COIN_BUILD_GLPK_FALSE,;t t
 s,@ASLLIB@,$ASLLIB,;t t
