Another try to fix env variables.

diff --git a/.github/workflows/windows-msvs-ci.yml b/.github/workflows/windows-msvs-ci.yml
--- a/.github/workflows/windows-msvs-ci.yml
+++ b/.github/workflows/windows-msvs-ci.yml
@@ -28,21 +28,11 @@ jobs:
       - name: Set up environment variables
         shell: cmd
         run: |
-          set
-          echo GITHUB_ENV - %GITHUB_ENV%
-          if "${{ matrix.platform }}"=="x64" ( 
-            echo "output_dir=x64\${{ matrix.configuration }}" >> "%GITHUB_ENV%"
-          ) else if "${{ matrix.platform }}"=="x86" (
-            echo "output_dir=${{ matrix.configuration }}" >> "%GITHUB_ENV%"
-          ) else (
-            echo "ERROR Unsupported platform '${{ matrix.platform }}'. Expecting x64 or x86." 1>&2
-            exit /b 1
-          )
-          if "${{ env.output_dir }}"=="" echo ERROR - No output_dir && exit 1
-
+          if "${{ matrix.platform }}"=="x64" echo "output_dir=x64\${{ matrix.configuration }}" >> %GITHUB_ENV%
+          if "${{ matrix.platform }}"=="x86" echo "output_dir=${{ matrix.configuration }}" >> %GITHUB_ENV%
+          if "${{ env.output_dir }}"=="" echo "ERROR - Unsupported platform '${{ matrix.platform }}'. Expecting x64 or x86." && exit 1
           echo "Output directory - ${{ env.output_dir }}"
-          echo "package_suffix=${{ matrix.os}}-msvs-v17-{{ matrix.configuration }}-{{ matrix.platform }}" >> "%GITHUB_ENV%"
-
+          echo "package_suffix=${{ matrix.os}}-msvs-v17-{{ matrix.configuration }}-{{ matrix.platform }}" >> %GITHUB_ENV%
       - name: Checkout source
         uses: actions/checkout@v4
         with:
